networks:
  databases:
    external: true
    name: databases

volumes:
  postgres_scema_data:
    driver: local
    name: postgres_scema_data

services:
  postgres_scema:
    image: pgvector/pgvector:pg15
    container_name: postgres_scema
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_scema_data:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: >
        pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    networks:
      - databases
